### ISSUE TITLE
Bugs in Spotify version 1.1.52.687.gf5565fe5-a with BlockTheSpot v0.51.0.0

### ISSUE THREAD

**Issue by Kell5719** [mrpond/BlockTheSpot#126] opened 2021-02-04 10:58 UTC
**Bug**
- Ad Banners area started showing up in today's Spotify update. (example in attachment) [Screenshot 1]
- Unable to pick "very high" Audio quality any more. [Screenshot 2]
![S1](https://user-images.githubusercontent.com/34344015/106882851-3327f780-671a-11eb-81be-6fb2b4e2fa2c.jpg)
![S2](https://user-images.githubusercontent.com/34344015/106882867-358a5180-671a-11eb-85ec-ab4476568b1e.png)
- Windows Defender still detects chrome_elf as a virus
- Banner removal not working

**Laptop:**
 - OS: Windows 10 Home Single Language Edition x64 (20H2)
 - Spotify Version: 1.1.52.687.gf5565fe5-a
 - BlockTheSpot Product Version: 0.51.0.0

**Comment by rednek46** [comment] 2021-02-04 12:09
@Kell5719 ,
High Quality option is not selectable by BTS. you will need premium for that.
Windows Defender Threat is a False Positive, Read Related issues like #96 #123 .
I cannot say anything about the ad banner right now. But If it is caused by the latest Spotify update, it will be fixed in the next release by @mrpond.

**Comment by Daksh777** [comment] 2021-02-04 15:52
From what I see, you are using some sort of alpha or beta version of Spotify. I have the same Spotify version as yours but without the "-a" and the UI of the app in your screenshot is also different from the normal version.
![image](https://user-images.githubusercontent.com/43648146/106918348-1fd35700-672f-11eb-8de2-7b57954418be.png)

**Comment by rednek46** [comment] 2021-02-04 16:46
@Kell5719, since it looks ok and BTS works fine on the normal version of Spotify, Im closing this issue.
You can ask Spotify support to opt out from alpha testing.

**Closed by rednek46** 2021-02-04 16:46 UTC
