### ISSUE TITLE
15 hours limit of free listening

### ISSUE THREAD

**Issue by domonbek** [mrpond/BlockTheSpot#79] opened 2020-10-19 09:01 UTC
I have encountered with 15 hours limit of free listening. Is it possible to reset 15 hours or completely remove it? Thank you.

![dsadww](https://user-images.githubusercontent.com/73104302/96423928-fdc3d080-1234-11eb-9b58-8a9959fc9d77.jpg)

**Comment by rednek46** [comment] 2020-10-19 10:44
> I have encountered with 15 hours limit of free listening. Is it possible to reset 15 hours or completely remove it? Thank you.
> 
> ![dsadww](https://user-images.githubusercontent.com/73104302/96423928-fdc3d080-1234-11eb-9b58-8a9959fc9d77.jpg)

Are you using BlockTheSpot?

**Comment by domonbek** [comment] 2020-10-19 11:04
> > I have encountered with 15 hours limit of free listening. Is it possible to reset 15 hours or completely remove it? Thank you.
> > ![dsadww](https://user-images.githubusercontent.com/73104302/96423928-fdc3d080-1234-11eb-9b58-8a9959fc9d77.jpg)
> 
> Are you using BlockTheSpot?

Yeah I'm using BlockTheSpot.

**Comment by mrpond** [comment] 2020-10-19 11:45
Did you trial some service of Spotify?
if not, try reproduce it with a newly-fresh register account.

**Comment by domonbek** [comment] 2020-10-20 11:07
> Did you trial some service of Spotify?
> if not, try reproduce it with a newly-fresh register account.

No trial or some service. I tried 3 accounts.
I am living in Japan. And I found out free account has 15hours limit in Japan. 
Is it possible to remove it by BlockTheSpot?
Thank you.

**Comment by rednek46** [comment] 2020-10-20 11:49
> > Did you trial some service of Spotify?
> > if not, try reproduce it with a newly-fresh register account.
> 
> No trial or some service. I tried 3 accounts.
> I am living in Japan. And I found out free account has 15hours limit in Japan.
> Is it possible to remove it by BlockTheSpot?
> Thank you.

I don't think location based restrictions can be removed by BlockTheSpot.  
I live in India and some songs are not available here.  
So what I did was to change my account location to US.  
The only issue then is that you have to use a VPN while logging in every 14 days to make Spotify believe that you are in US (I use some free VPN like Tunnel Bear as its only needed at the time of login and after that you don't need VPN for the next 14 days.).  
This gives me access to all the songs without any restrictions.  

But, if Incase @mrpond can remove this country based restrictions, it would be great.  
But I'm sure this is tied with user account so might not be able to avoid this any other way than using my method.

**Comment by Davoleo** [comment] 2020-10-20 13:53
yeah that 15 hours limit is only present in some countries like Japan
I use the exact same method @rednek46 uses to bypass country restrictions and I've also written a guide to do that as well with some other tricks you can apply to spotify, including BlockTheSpot, if you're interested you can read the gist [here](https://gist.github.com/Davoleo/de08de14934146847ef7fff070e4a04b)

**Comment by mrpond** [comment] 2020-10-23 03:42
@domonbek I'll look into it, maybe I need reverse engieer spotify websocket communication.

**Comment by LencoDigitexer** [comment] 2020-12-19 18:37
Прошу заметить, но я нашел одну закономерность. Если присоединить через Spotify Connect взломанный клиент на андроид и не взломанный на пк, то ПК запоминает алгоритм и даёт пропускать треки, даже если Connect отключен.

Please note, but I found one pattern. If you connect via Spotify Connect a hacked client on android and not hacked on a PC, then the PC remembers the algorithm and allows you to skip tracks, even if Connect is disabled

**Comment by rabilrbl** [comment] 2021-01-21 11:37
> > > Did you trial some service of Spotify?
> > > if not, try reproduce it with a newly-fresh register account.
> > 
> > 
> > No trial or some service. I tried 3 accounts.
> > I am living in Japan. And I found out free account has 15hours limit in Japan.
> > Is it possible to remove it by BlockTheSpot?
> > Thank you.
> 
> I don't think location based restrictions can be removed by BlockTheSpot.
> I live in India and some songs are not available here.
> So what I did was to change my account location to US.
> The only issue then is that you have to use a VPN while logging in every 14 days to make Spotify believe that you are in US (I use some free VPN like Tunnel Bear as its only needed at the time of login and after that you don't need VPN for the next 14 days.).
> This gives me access to all the songs without any restrictions.
> 
> But, if Incase @mrpond can remove this country based restrictions, it would be great.
> But I'm sure this is tied with user account so might not be able to avoid this any other way than using my method.

The dispute between warner chappel with spotify ended, now india has access to all of spotify music library.
https://techcrunch.com/2020/01/14/spotify-and-warner-chappell-end-dispute-in-india-sign-global-licensing-deal/

**Comment by LoveYourEnemy** [comment] 2021-07-15 19:23
Like @Nuzair46 said:
> The only issue then is that you have to use a VPN while logging in every 14 days to make Spotify believe that you are in US (I use some free VPN like Tunnel Bear as its only needed at the time of login and after that you don't need VPN for the next 14 days.).

I am in Japan, too. I use a VPN to locate myself to BC, Canada. 

**My question:**
1. Since I am using a VPN, does it mean that I have to change Skip_wpad to 1 mentioned by @mrpond ?
> The ad banner may appear if your network uses Web Proxy Auto-Discovery Protocol or not
Setting Skip_wpad = 1 in config.ini may help
I looked up on wiki, and I don't have a good understanding about whether vpn is applied to the Web Proxy Auto-Discovery Protocol or not.
Not sure if this will fix the ad problem, and I am testing now.

2. Does making chrome_elf.dll read-only help avoid applying patch every time after Spotify updates itself in the future?

**Comment by Nuzair46** [comment] 2021-07-17 14:37
@LoveYourEnemy 
1. Since you only use VPN once in 14 days to avoid tourist limit, there is no need to run the VPN everytime you open Spotify.
2. Haven't tried it yet, But the update installer will be initiated with system privileges, the "Read-Only" might be ignored and may get overwritten.

**Comment by Nuzair46** [comment] 2021-10-02 06:12
Closing this issue as its not being used for a long time.

**Closed by Nuzair46** 2021-10-02 06:12 UTC
Labels: enhancement
