### ISSUE TITLE
After opening Spotify 1st song lag 1/2 frame on first 1-5 sec

### ISSUE THREAD

**Issue by akashgfx** [mrpond/BlockTheSpot#348] opened 2022-03-20 17:04 UTC
Make sure you have completed everything in the following checklist.

 - [x] You are using the Spotify `last tested version` mentioned in the [README](https://github.com/mrpond/BlockTheSpot/blob/master/README.md).
 - [x] You are using the latest [BlockTheSpot](https://www.github.com/mrpond/BlockTheSpot/releases) from github.
 - [x] You uninstalled Spotify and just ran [BlockTheSpot.bat](https://raw.githack.com/mrpond/BlockTheSpot/master/BlockTheSpot.bat) and is still having issues.
 - [x] You read through the [known issues](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#known-issues) section in the README.
 - [x] You read through the [additional notes](https://github.com/mrpond/BlockTheSpot/blob/master/README.md#additional-notes) section in the README.
 - [x] You enabled logging by editing config.ini `set log = 1`.

### Describe the bug
A clear and concise description of what the bug is, along with your OS [eg. Windows 10]:

Windows 10

**Comment by CoolGuyMK** [comment] 2022-03-20 17:07
I've faced something like this recently too 
When I play a song it lags for 2-3 seconds and keeps repeating for 2-3 seconds

**Comment by akashgfx** [comment] 2022-03-20 17:08
> I've faced something like this recently too When I play a song it lags for 2-3 seconds and keeps repeating for 2-3 seconds

same repeating issue bro

**Comment by GhostSlayer** [comment] 2022-03-20 22:34
I'm having similar issues too. It repeats like 1 second of the track 2 times.

**Comment by kronics** [comment] 2022-03-21 03:18
same here. happened after updated S.... to latest version.

**Comment by 45O** [comment] 2022-03-21 03:24
Same here too

**Comment by FrappuccinoCaramel** [comment] 2022-03-21 03:32
I can also confirm this problem, it seems like Spotify did something to their code that now conflicts with BlockTheSpot.

@mrpond This unwanted interfere started upward of version 1.1.81.604.gccacfc8c, so 1.1.80.699.gc3dac750 is last version wherein your modifications work properply.

**Comment by FrappuccinoCaramel** [comment] 2022-03-21 03:33
I can also confirm this problem, it seems like Spotify did something to their code that now conflicts with BlockTheSpot.

@mrpond This unwanted interfere started upward of version 1.1.81.604.gccacfc8c, so 1.1.80.699.gc3dac750 is last version wherein your modifications work properly.

**Comment by Nuzair46** [comment] 2022-03-21 10:26
This issue appears for latest Spotify regardless of BlockTheSpot installed or not as it was tested and reported by others. This also doesn't occur for all users.

**Comment by whoamikyo** [comment] 2022-03-21 19:27
same here.

**Comment by AcelynnBen** [comment] 2022-03-22 00:25
Same problem here too

**Comment by JcdeA** [comment] 2022-03-22 12:45
Same issue here.

**Comment by Nuzair46** [comment] 2022-03-22 12:58
Im locking this issue as it is related to Spotify and will not be closed until Spotify fixes it. Please create a new issue if by chance you have something to update about this.

**Comment by Nuzair46** [comment] 2022-04-05 12:04
It seem that the problem is related to the lyrics, most songs without lyrics don't bug out while the ones with it do.
when the song keeps repeating, its Spotify trying to sync the lyrics with the song, you can notice this problem if u pause the song mid freeze while looking at the Lyrics

If there is a way to disable the lyrics through commands i think it should fix this problem
But officially lyrics cannot be disable

Currently using windows 10
- Author : @AcelynnBen

**Comment by Nuzair46** [comment] 2022-04-15 00:54
Issue seems to be fixed with latest Spotify release https://upgrade.spotify.com/upgrade/client/win32-x86/spotify_installer-1.1.83.954.gd226dfe8-18.exe

https://github.com/mrpond/BlockTheSpot/issues/358#issuecomment-1098956824

**Comment by Nuzair46** [comment] 2022-04-15 13:32
Closing this as Spotify update fixed the issue.

**Closed by Nuzair46** 2022-04-15 13:32 UTC
Labels: good first issue, invalid, wontfix
