### ISSUE TITLE
Getting Ads Again

### ISSUE THREAD

**Issue by Ailanz** [mrpond/BlockTheSpot#185] opened 2021-07-18 14:10 UTC
As of 2 days ago, ads (both banner and audio ads) are displaying again. 

Using the latest version of block the spot.

**Comment by Nuzair46** [comment] 2021-07-18 14:16
Make sure you are using [this](https://github.com/mrpond/blockthespot) repo.
Use the blockthespot.bat to automatically patch it.

closing as this is likely caused by using the master131's repo. reopen if not fixed.

**Comment by Ailanz** [comment] 2021-07-18 14:21
@Nuzair46 its not fixed. I'm using the suggested repo.

I even manually installed the chrome_elf.dll but ads are appearing ago. It was fine few days ago, jsut started having ads 2 days ago.

**Comment by Nuzair46** [comment] 2021-07-18 14:22
@Ailanz mention the Spotify version and upload the blockthespot log after enabling it in the config.ini.

**Comment by HardeNNN** [comment] 2021-07-18 14:53
I can confirm this also started happening to me, I was using the old spotify version with the old Blockthespot but then ads came back so I looked on google for an updated version and I found this one, I followed the instructions and it worked for a bit but I started getting ads again...

**Comment by Mylloon** [comment] 2021-07-18 16:17
I have been using blockthespot for a while and since today it doesn't work anymore

**Comment by AdeebIsmail** [comment] 2021-07-18 17:11
I had the same issue. Try this. 

-  Uninstall whatever version of Spotify you have currently
-  Install the latest Spotify version from the Spotify website
-  Run BlockTheSpot.Bat

**Comment by hyaku2003** [comment] 2021-07-18 19:55
> 
> 
> I had the same issue. Try this.
> 
>     * Uninstall whatever version of Spotify you have currently
> 
>     * Install the latest Spotify version from the Spotify website
> 
>     * Run BlockTheSpot.Bat

thanks, this worked for me!

**Comment by MDproductions-dev** [comment] 2021-07-18 19:55
This happened to me too, idk if its the same issue but try deinstalling the latest windows security update (KB5004237). That fixed it for me.

**Comment by Ailanz** [comment] 2021-07-18 20:39
Yes that seemed to solve it. Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by HardeNNN** [comment] 2021-07-18 22:20
Reinstalling and running blockthespot again only works for a bit then we get ads again...

**Comment by heirloom77** [comment] 2021-07-19 03:28
Created this account just to say that i had been using this hack for years but now the ads are showing up again out of nowhere.

**Comment by Nuzair46** [comment] 2021-07-19 05:58
Please attach the Spotify version that you are currently using and experiencing issues. 

BlockTheSpot from this repo only works for the latest version of Spotify.

**Comment by Nuzair46** [comment] 2021-07-19 14:33
Provide the version of the client as this is likely an issue caused by using the old version of Spotify.

**Comment by HardeNNN** [comment] 2021-07-19 14:34
![image](https://user-images.githubusercontent.com/42101418/126177364-ffa73694-dea2-4b8c-b04c-f564b68443e8.png)

**Closed by Nuzair46** 2021-07-19 14:33 UTC

**Comment by HardeNNN** [comment] 2021-07-19 14:35
It works for a while after running Blockthespot but eventually ads come back, re-running the script fixes it but maybe they implemented an auto update type of thing or idk...

**Comment by Nuzair46** [comment] 2021-07-19 14:36
@HardeNNN enabling logging in config.ini and then upload it here once you encounter the ad.

**Comment by heirloom77** [comment] 2021-07-19 15:43
i downloaded the new version but i'm also having the same issues
Also there is this black thing were the ads once were
![u3gn2r](https://user-images.githubusercontent.com/87629148/126187957-7acbbb29-cb0c-46c1-ace1-0fd38abfbcec.png)
