### ISSUE TITLE
INSANELY slow speeds when using powershell command instead of batch script?

### ISSUE THREAD

**Issue by RealFX-Code** [mrpond/BlockTheSpot#340] opened 2022-03-12 13:05 UTC
Using: "Powershell Core 7.3.0-preview.2" combined with "Windows 11 22000.556"

Heyo, i've tried adding the option to re-install spotify with BlockTheSpot to my powershell profile, and it seems to be waaaay slower than the batch file that is released here in the repo. I don't know why, but it seems like it's being limited by something?
https://streamable.com/vq49qg

From the video linked above you can see how ridiculously slow it is, 16K a second... The code inside 'spotifyupdate' is:
`function spotifyupdate {
	Write-Output "Attempting to update spotify..."
	[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12; Invoke-Expression "& { $(Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/mrpond/BlockTheSpot/master/install.ps1') } -UninstallSpotifyStoreEdition -UpdateSpotify -RemoveAdPlaceholder"
}`

BTW: The batch script works as fast as it can, literally instant downloads. I don't know why it's so slow in the powershell command.

**Comment by RealFX-Code** [comment] 2022-03-12 13:09
I forgot to mention, I get the error below everytime i try to install BlockTheSpot on my pc.
`WARNING: Module Appx is loaded in Windows PowerShell using WinPSCompatSession remoting session; please note that all input and output of commands from this module will be deserialized objects. If you want to load this module into PowerShell please use 'Import-Module -SkipEditionCheck' syntax.`

**Comment by Nuzair46** [comment] 2022-03-13 06:43
From what I can think of, this looks like an issue when `BitsTransfer` is not found on the current shell you are using.

https://github.com/mrpond/BlockTheSpot/blob/3b13d997a58ea8d5b036c6a7508f6b4fb1de82f4/install.ps1#L18-L88

In this script, we use this function to determine which downloader to use. If `BitsTransfer` is found, then we just download it with that. This might be working when the bat script is used. And when you are using your custom script I think the BitsTransfer is not being detected, instead the custom downloader is being used. This might be the cause for the slower downloads but I'm not sure on this. An interesting issue about the same is here in this [stackoverflow](https://stackoverflow.com/questions/28682642/powershell-why-is-using-invoke-webrequest-much-slower-than-a-browser-download).

If possible can you try editing this function to include this fix mentioned in the above stackoverflow and try with that. Let us know how it goes.
You will only need to make changes to the `else` block of the above function.

**Comment by KUTlime** [comment] 2022-03-13 07:48
* `BitTransfer` will never be used for this version of PowerShell.
* The link to StackOverflow is irrelevant. It describes a different problem. We do not use `Invoke-WebRequest` in the BTW install script.
* This version of PowerShell is in the preview state. The problem can be somewhere in PowerShell runtime. I would wait at least for RC version.
* It is a network related problem. This could be @RealFX-Code specific.

**Comment by Nuzair46** [comment] 2022-03-20 13:17
Closing as this is likely caused by the reasons KUTlime explained.

**Closed by Nuzair46** 2022-03-20 13:17 UTC
