### ISSUE TITLE
I don't have the lyrics but others features work

### ISSUE THREAD

**Issue by LeMaxicien** [mrpond/BlockTheSpot#537] opened 2024-05-09 18:11 UTC
![image](https://github.com/mrpond/BlockTheSpot/assets/165584772/b5fdfa40-a8f7-4901-a9ce-19e8665b05c4)

**Comment by Vilo659** [comment] 2024-05-09 19:38
i have the same issue pal

**Comment by ampethamine** [comment] 2024-05-10 09:01
Comments can be unblocked through the debug window. Click on the three dots upper left corner > Develop > Show Debug Window >Remote Configs > Search for lyric > Set "enableLyricsUpsell" to false.

**Comment by ampethamine** [comment] 2024-05-10 09:04
Also duplicate of #535

**Comment by grloper** [comment] 2024-05-11 01:56
same, no lyrics

**Comment by invinciblevenom** [comment] 2024-05-11 23:12
> Some of the lyrics can be unblocked through the debug window but you still need premium to view full lyrics. Click on the three dots upper left corner > Develop > Show Debug Window >Remote Configs > Search for lyric > Set "enableLyricsUpsell" to false.

This does remove the premium banner but unlocks lyrics partially and they aren't time synced.

**Comment by invinciblevenom** [comment] 2024-05-11 23:14
> same, no lyrics

They are not working after 1.2.37.701.ge66eb7bc update.

**Comment by ChiefEKD19** [comment] 2024-05-14 06:10
fully uninstalled spotify and downgraded to a version that was working previously (1.2.36.959) and i still cant see lyrics after using the patch?

**Comment by ampethamine** [comment] 2024-05-14 06:17
> fully uninstalled spotify and downgraded to a version that was working previously (1.2.36.959) and i still cant see lyrics after using the patch?

Lyrics are now a server sided premium feature and won't work on any version now

**Comment by invinciblevenom** [comment] 2024-05-14 11:09
> > fully uninstalled spotify and downgraded to a version that was working previously (1.2.36.959) and i still cant see lyrics after using the patch?
> 
> Lyrics are now a server sided premium feature and won't work on any version now

This applies to Spotify Desktop?

**Comment by Nuzair46** [comment] 2024-05-14 11:52
duplicate #535

**Closed by Nuzair46** 2024-05-14 11:52 UTC
