### ISSUE TITLE
latest chrome_elf virus?

### ISSUE THREAD

**Issue by mapper14** [mrpond/BlockTheSpot#96] opened 2020-12-14 15:38 UTC
Latest version of chrome_elf posted here is being reported by Win 10 MS Defenders as virus threat.  Is this a false positive?

**Comment by rednek46** [comment] 2020-12-14 15:50
Yes, it is a false positive.
Please update your Defender definitions.
You can add it to exclusion or refer to #39 to prevent this happening.

**Comment by rednek46** [comment] 2020-12-14 15:51
I opened it so that anyone else facing this issue can continue here for the time being.

**Comment by J0EYBOY** [comment] 2020-12-15 05:38
Mine detected it as a Trojan, what about yours?

**Comment by J0EYBOY** [comment] 2020-12-15 05:39
> Latest version of chrome_elf posted here is being reported by Win 10 MS Defenders as virus threat. Is this a false positive?

Mine was detected as a trojan, was yours also or was it just mine?

**Comment by rednek46** [comment] 2020-12-15 05:44
@J0EYBOY Its a false positive and will be fixed by @mrpond . in the meantime refer to #39 to avoid this issue for now.

**Comment by UnnieChaeng** [comment] 2020-12-15 10:33
is it true or just a lie? I'm scared right now

**Comment by rednek46** [comment] 2020-12-15 10:39
@UnnieChaeng Yes it is, If you used the Blockthespot.bat or manually installed the patch from this repo, then it is safe.
You are free to verify the source code yourself.

**Comment by mrpond** [comment] 2020-12-16 05:15
Hello, please try again.
BlockTheSpot had Appveyor's CI integrated. 
somethings wrong with Apppveyor compiler (ofc it safe, binary diff check had been done).

I remove 2 new Appveyor release , these bat will download my computer compile release instead.
should working fine now.

**Closed by mrpond** 2020-12-16 05:15 UTC
Labels: help wanted

**Comment by S-Simon** [comment] 2020-12-24 11:39
This is still an issue. I get that it's a false positive, but can it be fixed?

**Comment by rednek46** [comment] 2020-12-24 14:17
@S-Simon you can download the source in your system and build it there. It wont show any threat.
This issue is caused by the automated packaged build by [Appveyor](https://www.appveyor.com/). They need to fix it in their end afaik. 

Also The latest release is not from AppVeyor, it was compiled on mrpond's system, So it wont trigger any threat.
So your options is use the bat file to download and install the latest patch or manually compile the code in your system..

**Comment by mapper14** [comment] 2020-12-24 19:44
Where's the link to latest patch as mentioned by rednek46 that doesn't trigger false positive in Win Defender? (and BTW also triggers has Malwarebytes on my win system as an extreme threat)

**Comment by rednek46** [comment] 2020-12-24 19:54
@mapper14 release #26FIX or use the blockthespot.bat , it will install the right patch.

**Comment by rednek46** [comment] 2021-01-11 07:18
@mrpond Is it possible to use [this](https://github.com/actions/starter-workflows/blob/b20b76eb795a7c869d4c2a1adf166d10448ec758/ci/msbuild.yml) instead of appveyor to avoid the false positive?

**Comment by exodius48** [comment] 2021-01-30 02:41
![2021-01-30_093909](https://user-images.githubusercontent.com/9832875/106344926-3288fe80-62df-11eb-8bdc-40e7f05f4eb4.png)

Latest chrome_elf detected as trojan by symantec endpoint security
