### ISSUE TITLE
Spotify Reinstalls with Ads

### ISSUE THREAD

**Issue by Mark33333** [mrpond/BlockTheSpot#326] opened 2022-02-17 18:45 UTC
Since installing BlockTheSpot on my laptop, the Spotify desktop app twice reinstalled when attempting to open the app.  It reinstalled with ads.  I needed to uninstall Spotify and reinstall BlockTheSpot in order to block the ads again.  How can I prevent Spotify from reinstalling with ads with BlockTheSpot installed?  Thanks.

**Comment by Nuzair46** [comment] 2022-02-17 19:20
Running the bat file should just install Spotify once if its outdated and then apply the patch automatically.

**Comment by Mark33333** [comment] 2022-02-17 19:42
> 

That's what I thought.  Any ideas why this occurred twice for me?  Thanks.

**Comment by Luis-Ambrozin** [comment] 2022-02-17 19:56
Just get the same here, tried to run again the bat file, did not work, probably is some spotify update

**Comment by Nuzair46** [comment] 2022-02-17 21:47
Can you guys share your current Spotify version?

**Comment by Mark33333** [comment] 2022-02-18 03:07
> Can you guys share your current Spotify version?

Where can I find this info?

**Comment by Mark33333** [comment] 2022-02-18 03:14
> Can you guys share your current Spotify version?

I found it - Spotify for Windows 1.1.79.763.gc2965cdf.  This was the version that was installed by BlockTheSpot.  It does not display ads.

**Comment by Nuzair46** [comment] 2022-02-18 13:14
Since you have the supported version, Block the spot should not ask for update prompt. If it asks, just press "n".
Make sure you are running either the bat file or the first powershell command.
There is a new automated powershell command, this will update spotify without any user action.

closing this issue as I think it was caused by using the automated ps script. Please reopen if you face further issues related to this.

**Closed by Nuzair46** 2022-02-18 13:14 UTC
