### ISSUE TITLE
shuffle and back button greys out + ads start after few songs

### ISSUE THREAD

**Issue by neighpalm** [mrpond/BlockTheSpot#109] opened 2021-01-07 05:22 UTC
I am unable to unshuffle the playlist that I am listening to after I start playing in the app. In the beginning, it is alright and I can seek different times within the song I listen to but after a few songs that disappear and the shuffle button greys out. Also, I cannot go back and listen to previous songs once they have been played i.e. the back button is greyed out as well.
the ads in between the songs start popping in after as well when this happens. I've changed the config.ini and set Log = 1 as well.

I have tried uninstalling>reinstalling Spotify more than once and verified that I am copying the latest chrome_elf.dll.
I can post screenshots if need be.
Thanks.

Desktop:

OS: Windows 10
Spotify Version: 1.1.48.625.g1c87c7f7
BlockTheSpot Product Version: 0.51.0.0

[main_log.txt](https://github.com/mrpond/BlockTheSpot/files/5779720/main_log.txt)
[utility_log.txt](https://github.com/mrpond/BlockTheSpot/files/5779721/utility_log.txt)

**Comment by mrpond** [comment] 2021-01-07 07:29
Hi please reapply patch and test again, 
I add some log and check.

**Comment by neighpalm** [comment] 2021-01-07 19:37
Hey,

I tried the new patch but after 3 songs the ads start again.
[main_log.txt](https://github.com/mrpond/BlockTheSpot/files/5783609/main_log.txt)
[utility_log.txt](https://github.com/mrpond/BlockTheSpot/files/5783610/utility_log.txt)

**Comment by mrpond** [comment] 2021-01-08 07:17
upload blockthespot_log.txt instead

**Comment by neighpalm** [comment] 2021-01-08 07:53
[blockthespot_log.txt](https://github.com/mrpond/BlockTheSpot/files/5785836/blockthespot_log.txt)

**Comment by mrpond** [comment] 2021-01-08 21:49
ok please test 2021.1.08.30

**Comment by neighpalm** [comment] 2021-01-08 23:35
Update: Ads are still showing up. Someone told me that accounts that were Premium before had this issue and mine is like that.
[blockthespot_log.txt](https://github.com/mrpond/BlockTheSpot/files/5789763/blockthespot_log.txt)

**Comment by mrpond** [comment] 2021-01-11 14:41
Hi, you use facebook login? can try with normal account instead?

at the moment , I can't reproduce this bug at my side

**Comment by neighpalm** [comment] 2021-01-11 16:48
I use my normal username login or e-mail login.

**Comment by mrpond** [comment] 2021-01-19 13:28
can you copy&paste config.ini here?

**Comment by mrpond** [comment] 2021-03-24 09:57
close this issue, please create new issue if still have a problem.

**Closed by mrpond** 2021-03-24 09:57 UTC
Labels: bug, help wanted
