### ISSUE TITLE
chrome_elf.dll Virus?

### ISSUE THREAD

**Issue by Sn8ow** [mrpond/BlockTheSpot#308] opened 2022-01-22 16:10 UTC
![image](https://user-images.githubusercontent.com/80784394/150646485-02065dab-49dc-4b75-8971-c00244a501f5.png)

WHY?

**Comment by Davoleo** [comment] 2022-01-22 16:51
Duplicate of #128

**Comment by Nuzair46** [comment] 2022-01-22 17:34
False positive. you can go through the codebase to confirm this.

**Closed by Nuzair46** 2022-01-22 17:34 UTC
